version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./projects/:/projects/
      - ./volumes/log/:/var/log/nginx/
      - ./volumes/cert/:/etc/nginx/cert/
      - ./volumes/conf.d/:/etc/nginx/conf.d/
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf
